package.json

cc @diasdavid 
I started working on integrating floodsub into js-ipfs and am still having path issues when using the existing package. I saw [this request closed](https://github.com/libp2p/js-libp2p-floodsub/pull/6) already, but since the issue still stands, now seemed like a good time to re-open the conversation and see if we can get to resolution :)
As such, this request's change is informed by the comment thread from the link above and [the js guidelines](https://github.com/ipfs/community/blob/master/js-project-guidelines.md#default-require). Thanks!

Resolve package.json path issue

---

package.json
src/message/index.js
src/message/rpc.proto.js
src/message/topic-descriptor.proto.js

This PR will remove the dependency on fs module and will fix the browser version.
Previously the .proto files were read with fs.readFileSync() from .proto files. This PR will change it so that the .proto files are now .proto.js files and they get required in message/index.js, which seems to be the way in other js-ipfs modules. This removes the dependency on fs and makes it easier to deal with the browser version.
This PR will also add webpack@2.1.0-beta.25 as a dev dependency because webpack@2.1.0-beta.26 seems to break the build process.
This PR will also update package.json to use latest aegir release.

Remove fs dependency

---

package.json
src/dial-floodsub.js
test/2-nodes.js

This fix ensures that a node's current subscriptions are immediately passed to a new peer when a connection is established.

fix: pass subscriptions immediately on new peer connection

---

src/index.js
test/2-nodes.js
test/multiple-nodes.js

This PR will fix the floodsub's internal connection error handling. 
There was a missing argument on call to _onConnectionEnd() in _processConnection(), which meant that the peer that errored (eg. on connection end) was never removed from the state of floodsub (`.peers`). This in turn caused the bug where upon one peer disconnecting and coming back, the peers were not re-connected nor able to communicate with each other. This bug is fixed with this PR (verified in orbit).
So, if you've seen the behaviour where peers don't reconnect, this was the reason.
cc @VictorBjelkholm I think you experienced this in some of your demos, so fyi.

Fix connection error handling

---

src/index.js

Upon error or already connected, `._dialPeer` wasn't calling back.

fix: _dialPeer always calls back

---

.travis.yml
src/index.js
src/message/rpc.proto.js
test/2-nodes.js

JS implementation has renamed the field `topicIDs` to `topicCIDs`, see the [Message spec](https://github.com/libp2p/specs/tree/master/pubsub#the-message). This is not a good idea.  See [background discussion](https://github.com/ipfs/js-ipfs/issues/1068)

Published message field names

---

package.json
src/index.js
src/message/rpc.proto.js
src/peer.js
src/utils.js
test/2-nodes.js
test/multiple-nodes.js
test/utils.spec.js

Some of the issues were introduced by me in https://github.com/libp2p/js-libp2p-floodsub/pull/49.  Basically, the field `topicCIDs` is used in RPC messages and `topicIDs` in API messages.
See issue #50
Summary of changes
- multiple peer connections
- RPC message changed to have binary `from`
- Avoid race conditions, by quietly ignoring unsub when shutdown

Various floodsub issues

---

src/base.js
src/index.js

While studying the repo I broke out the boilerplate of managing the connected peers and dialing flow into `BaseProtocol`. This could be published as a standalone module to help making building protocols easier.

feat: breakout BaseProtocol boilerplate code

---

src/index.js
src/utils.js
test/utils.spec.js

fix: ignore message false positive

---

src/base.js
test/2-nodes.js

My previous [double dialing fix](https://github.com/libp2p/js-libp2p-floodsub/pull/63) introduced a bug that would prevent floodsub from ever dialing again after an error (sorry!)
This PR fixes the bug

fix: allow dials even after error

---

package.json
src/index.js

The inherited PubSubProtocol class already contains a time-cache for
latest seen messages. Use the existing cache instead of creating a
duplicate.

fix: use pubsub seenCache

---

package.json
src/index.js

The new publish callback will default to a noop function.
All published messages will be signed.
Requires https://github.com/libp2p/js-libp2p-pubsub/pull/17
Ref: https://github.com/libp2p/js-libp2p-pubsub/issues/16

feat: add support for signing

---

benchmarks/README.md
benchmarks/index.js

With updates on `js-libp2p` and `js-libp2p-floodsub`, the benchmarks got broken.

chore: update benchmark

---

src/index.js
test/pubsub.spec.js

Added export for multicodec, so that Gossipsub can use it, when tries to fallback a dial to floodsub

chore: export multicodec

---

package.json
src/index.js
test/pubsub.spec.js

BREAKING CHANGE: If messages are not being signed, this change will result in them being dropped. A previous release of floodsub added signing by default, but any Floodsub version older than `v0.16.0` will have their messages dropped. This is inline with the latest go pubsub behavior.
Depends on https://github.com/libp2p/js-libp2p-pubsub/pull/20
Signed messages are now validated. If `strictSigning` is enabled (it is by default), messages **must** be signed.

feat: add strict signing validation for messages

---

README.md
src/index.js
test/emit-self.spec.js

In `libp2p-floodsub` we currently do emit to self all the times. However, there are several use cases, where we may not want that, and in this context, I added an option to disable it in `libp2p-floodsub`. 
I will open an issue on [libp2p/js-libp2p-pubsub](https://github.com/libp2p/js-libp2p-pubsub) for discussing which should be the default behavior from `js-libp2p` users, as I discussed previously with @jacobheun .

feat: optional self emit

---

src/index.js

Pass options to `PubsubBaseProtocol` constructor, so can configure the following options:
**signMessages** if messages should be signed, defaults to true
**strictSigning** if message signing should be required, defaults to true

feat: pass options to base protocol constructor

---

README.md
src/index.js
test/2-nodes.spec.js
test/multiple-nodes.spec.js
test/pubsub.spec.js

BREAKING CHANGE: messages are not self emitted by default anymore. You need to set the emitSelf option to true to use it
On the context of [libp2p/js-libp2p-pubsub#22](https://github.com/libp2p/js-libp2p-pubsub/issues/22), `emitSelf` option defaults to false

chore: emit self default to false

---

README.md
package.json
src/index.js
test/2-nodes.spec.js
test/emit-self.spec.js
test/multiple-nodes.spec.js
test/pubsub.spec.js
test/utils/index.js

In the context of deprecating `peer-info` as described on [libp2p/js-libp2p#589](https://github.com/libp2p/js-libp2p/issues/589), this PR removes the `peer-info` usage on pubsub internal peer data structure. Moreover, this uses the new topology API, which also uses `peer-id` instead of `peer-info`
BREAKING CHANGE: using new topology api with peer-id instead of peer-info and new pubsub internal peer data structure
Needs:

chore: remove peer-info usage

---

package.json
test/2-nodes.spec.js
test/multiple-nodes.spec.js

This PR makes libp2p pubsub subsystem use unidirectional streams instead of bidirectional streams per discussion on [ipfs/go-ipfs#7390](https://github.com/ipfs/go-ipfs/issues/7390).
More details about the reasoning for this can be found in https://discuss.libp2p.io/t/gossip-questions/257/6
This PR replicates #105 for the `0.20.x` version range of `libp2p-floodsub`
Bear in mind that a lot of this "connection logic" can be abstracted. I did not worry about it and just followed what we already had in floodsub and gossipsub. Hopefully, after `gossipsub@1.1`, I want to create the libp2p pubsub interface and move/refactor the tests there and re-use most of them in all our router implementations.
Needs:

fix: use unidirectional streams v0.20.x

---

package.json
test/2-nodes.spec.js
test/multiple-nodes.spec.js

This PR makes libp2p pubsub subsystem use unidirectional streams instead of bidirectional streams per discussion on [ipfs/go-ipfs#7390](https://github.com/ipfs/go-ipfs/issues/7390).
More details about the reasoning for this can be found in https://discuss.libp2p.io/t/gossip-questions/257/6
I have tested this change on all libp2p repos: `js-libp2p`, `libp2p-daemon` and `interop` and everything is working properly. The tests here need to be updated though, as a result of the tests being implemented considering a bidirectional stream.
Bear in mind that a lot of this "connection logic" can be abstracted. I did not worry about it and just followed what we already had in floodsub and gossipsub. Hopefully, after `gossipsub@1.1`, I want to create the libp2p pubsub interface and move/refactor the …

fix: use unidirectional streams

---

README.md
package.json
src/index.js
test/2-nodes.spec.js
test/emit-self.spec.js
test/multiple-nodes.spec.js
test/pubsub.spec.js

Replaces all use of node Buffers with Uint8Arrays
BREAKING CHANGES:
- The `.data` property of received pubsub messages was a Buffer, now it is a Uint8Array
- All deps of this module use Uint8Arrays

fix: replace node buffers with uint8arrays

---

package.json

libp2p@0.29.0 was released so we can go back to regular semver for the required version number.

chore: remove gh dep from peer deps

---

package.json
src/index.js
test/floodsub.spec.js
test/utils/create-peer.js

This PR updates the dependencies. 
`libp2p-interfaces` pubsub had breaking changes:
- `this.getMsgId` now returns `Uint8Array`
- `_buildMessage` now creates `seqNo` and not receive it
BREAKING CHANGE: signing policy added instead of strictsigning options

chore: update deps

---

.github/workflows/main.yml
package.json

We added peer deps to signal to the user that they should add the modules they depend on as deps of their project.
Starting with npm7 all peer deps get installed automatically which defeats the purpose of our use of peer deps, so let's remove them.

chore: remove peer deps

---

.github/workflows/main.yml
package.json

This PR updates libp2p interfaces to run all pubsub subsystem tests, moving the ownership of libp2p tests to the modules. Context https://github.com/libp2p/js-libp2p/issues/857
Needs:

chore: update pubsub interface to run subsystem tests

---

.aegir.js
.github/workflows/main.yml
package.json
src/index.js
test/compliance.spec.js
test/floodsub.spec.js

BREAKING CHANGE: uses new multiaddr, libp2p-interfaces, etc

chore: update dependencies

---

package.json
test/floodsub.spec.js

Refactors interfaces and classes used by `libp2p-interfaces` to use the async peer store from https://github.com/libp2p/js-libp2p/pull/1058
BREAKING CHANGE: peerstore methods are now all async

feat: async peerstore

---

package.json
src/index.ts
src/message/rpc.d.ts
src/message/rpc.js
src/message/rpc.proto
test/compliance.spec.ts
test/floodsub.spec.ts
tsconfig.json

Updates to latest code from https://github.com/libp2p/js-libp2p-interfaces/pull/180

fix: update interfaces

---

README.md
package.json
src/index.ts
src/message/rpc.ts
test/compliance.spec.ts
test/floodsub.spec.ts

`@libp2p/components` is a choke-point for our dependency graph as it depends on every interface, meaning when one interface revs a major
`@libp2p/components` major has to change too which means every module depending on it also needs a major.
Switch instead to constructor injection of simple objects that let modules declare their dependencies on interfaces directly instead of
indirectly via `@libp2p/components`
Refs libp2p/js-libp2p-components#6
BREAKING CHANGE: modules no longer implement `Initializable` instead switching to constructor injection

fix!: remove @libp2p/components

---

package.json

The CID class has breaking changes in v11 so update all deps to the latest version.

fix!: update multiformats to v11
